FROM node:22.12.0

WORKDIR /app

RUN yarn global add gatsby-cli prettier

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

EXPOSE 8000

CMD ["yarn", "develop", "-H", "0.0.0.0"]
