backend:
  name: git-gateway
  repo: TUNAFE/Website
  # Path to your Github repository (blanked out on purpose)
  branch: feature/collections

publish_mode: editorial_workflow
media_folder: "static/img"
public_folder: "/img"

collections:
  # sobre-nos/membros
  - label: "Magister"
    name: "magister"
    folder: "_content/sobre-nos/membros/atualmente/magister"
    create: true
    identifier_field: name
    slug: "{{fileNumber}}-{{slug}}"
    fields:
      - {label: "NumeroFicheiro", name: "fileNumber", widget:"string" , required:"true"}
      - {label: "Nome" , name: "name", widget:"string" , required:"true"}
      - {label: "NomeCompleto" , name: "nameFull", widget:"string" , required:"true"}
      - {label: "NomeCivil", name: "nameC", widget:"string" , required:"true"}
      - {label: "Curso", name: "course", widget:"string" , required:"true"}
      - {label: "Madrinha", name: "godmother", widget:"string" , required:"true"}
      - {label: "Instrumentos", name: "instruments", widget:"string" , required:"true"}
      - {label: "Foto", name: "picture", widget:"string" , required:"true"}
  - label: "Atuais Mestre-Tunas"
    name: "atuais-mestre-tunas"
    folder: "_content/sobre-nos/membros/atualmente/mestre-tunas"
    create: true
    identifier_field: name
    slug: "{{fileNumber}}-{{slug}}" # the default for the slug is the identifier_field
    fields:
      - {label: "NumeroFicheiro", name: "fileNumber", widget:"string" , required:"true"}
      - {label: "Nome" , name: "name", widget:"string" , required:"true"}
      - {label: "NomeCompleto" , name: "nameFull", widget:"string" , required:"true"}
      - {label: "NomeCivil", name: "nameC", widget:"string" , required:"true"}
      - {label: "Curso", name: "course", widget:"string" , required:"true"}
      - {label: "Madrinha", name: "godmother", widget:"string" , required:"true"}
      - {label: "Instrumentos", name: "instruments", widget:"string" , required:"true"}
      - {label: "Foto", name: "picture", widget:"string" , required:"true"}
  - label: "Atuais Tunas"
    name: "atuais-tunas"
    folder: "_content/sobre-nos/membros/atualmente/tunas"
    create: true
    identifier_field: name
    slug: "{{fileNumber}}-{{slug}}"
    fields:
      - {label: "NumeroFicheiro", name: "fileNumber", widget:"string" , required:"true"}
      - {label: "Nome" , name: "name", widget:"string" , required:"true"}
      - {label: "NomeCompleto" , name: "nameFull", widget:"string" , required:"true"}
      - {label: "NomeCivil", name: "nameC", widget:"string" , required:"true"}
      - {label: "Curso", name: "course", widget:"string" , required:"true"}
      - {label: "Madrinha", name: "godmother", widget:"string" , required:"true"}
      - {label: "Instrumentos", name: "instruments", widget:"string" , required:"true"}
      - {label: "Foto", name: "picture", widget:"string" , required:"true"}
  - label: "Atuais Caloiras"
    name: "atuais-caloiras"
    folder: "_content/sobre-nos/membros/atualmente/caloiras"
    create: true
    identifier_field: name
    slug: "{{fileNumber}}-{{slug}}"
    fields:
      - {label: "NumeroFicheiro", name: "fileNumber", widget:"string" , required:"true"}
      - {label: "Nome" , name: "name", widget:"string" , required:"true"}
      - {label: "NomeCompleto" , name: "nameFull", widget:"string" , required:"true"}
      - {label: "NomeCivil", name: "nameC", widget:"string" , required:"true"}
      - {label: "Curso", name: "course", widget:"string" , required:"true"}
      - {label: "Madrinha", name: "godmother", widget:"string" , required:"true"}
      - {label: "Instrumentos", name: "instruments", widget:"string" , required:"true"}
      - {label: "Foto", name: "picture", widget:"string" , required:"true"}
  - label: "Antigas Mestre-Tunas"
    name: "antigas-mestre-tunas"
    folder: "_content/sobre-nos/membros/sempre-tunafas/mestre-tunas"
    create: true
    identifier_field: name
    slug: "{{fileNumber}}-{{slug}}"
    fields:
      - {label: "NumeroFicheiro", name: "fileNumber", widget:"string" , required:"true"}
      - {label: "Nome" , name: "name", widget:"string" , required:"true"}
      - {label: "NomeCompleto" , name: "nameFull", widget:"string" , required:"true"}
      - {label: "NomeCivil", name: "nameC", widget:"string" , required:"true"}
      - {label: "Curso", name: "course", widget:"string" , required:"true"}
      - {label: "Madrinha", name: "godmother", widget:"string" , required:"true"}
      - {label: "Instrumentos", name: "instruments", widget:"string" , required:"true"}
      - {label: "Foto", name: "picture", widget:"string" , required:"true"}
  - label: "Antigas Tunas"
    name: "antigas-tunas"
    folder: "_content/sobre-nos/membros/sempre-tunafas/tunas"
    create: true
    identifier_field: name
    slug: "{{fileNumber}}-{{slug}}"
    fields:
      - {label: "NumeroFicheiro", name: "fileNumber", widget:"string" , required:"true"}
      - {label: "Nome" , name: "name", widget:"string" , required:"true"}
      - {label: "NomeCompleto" , name: "nameFull", widget:"string" , required:"true"}
      - {label: "NomeCivil", name: "nameC", widget:"string" , required:"true"}
      - {label: "Curso", name: "course", widget:"string" , required:"true"}
      - {label: "Madrinha", name: "godmother", widget:"string" , required:"true"}
      - {label: "Instrumentos", name: "instruments", widget:"string" , required:"true"}
      - {label: "Foto", name: "picture", widget:"string" , required:"true"}
  - label: "Antigas Caloiras"
    name: "antigas-caloiras"
    folder: "_content/sobre-nos/membros/sempre-tunafas/caloiras"
    create: true
    identifier_field: name
    slug: "{{fileNumber}}-{{slug}}"
    fields:
      - {label: "NumeroFicheiro", name: "fileNumber", widget:"string" , required:"true"}
      - {label: "Nome" , name: "name", widget:"string" , required:"true"}
      - {label: "NomeCompleto" , name: "nameFull", widget:"string" , required:"true"}
      - {label: "NomeCivil", name: "nameC", widget:"string" , required:"true"}
      - {label: "Curso", name: "course", widget:"string" , required:"true"}
      - {label: "Madrinha", name: "godmother", widget:"string" , required:"true"}
      - {label: "Instrumentos", name: "instruments", widget:"string" , required:"true"}
      - {label: "Foto", name: "picture", widget:"string" , required:"true"}
  # homepage
  - label: "Contactos"
    name: "contactos"
    folder: "_content/homepage"
    create: true
    identifier_field: fileName
    slug: "{{fileName}}"
    fields:
      - {label: "Titulo do Ficheiro", name: "fileName", widget:"string" , required:"true"}
      - {label: "Nome RP" , name: "nameRP", widget:"string" , required:"true"}
      - {label: "Contacto RP" , name: "mobileRP", widget:"string" , required:"true"}
      - {label: "Nome Magister", name: "nameMagister", widget:"string" , required:"true"}
      - {label: "Contacto Magister", name: "mobileMagister", widget:"string" , required:"true"}
      - {label: "Email TUNAFE", name: "email", widget:"string" , required:"true"}
      - {label: "Morada TUNAFE", name: "address", widget:"string" , required:"true"}
  - label: "Ensaios"
    name: "ensaios"
    folder: "_content/homepage"
    create: true
    identifier_field: fileName
    slug: "{{fileName}}"
    fields:
      - {label: "Titulo do Ficheiro", name: "fileName", widget:"string" , required:"true"}
      - {label: "Dias da semana" , name: "weekDays", widget:"string" , required:"true"}
      - {label: "Sala de ensaio" , name: "rehearsalRoom", widget:"string" , required:"true"}
      - {label: "Sala da Tuna", name: "tunaRoom", widget:"string" , required:"true"}
      - {label: "Hora inicio ensaio", name: "startTime", widget:"string" , required:"true"}
      - {label: "Hora fim ensaio", name: "finishTime", widget:"string" , required:"true"}
