backend:
  name: git-gateway
  repo: TUNAFE/Website
  # Path to your Github repository (blanked out on purpose)
  branch: feature/collections

publish_mode: editorial_workflow
media_folder: "static/img"
public_folder: "/img"

collections:
  # sobre-nos/membros
  - label: "Magister"
    name: "magister"
    folder: "_content/sobre-nos/membros/atualmente/magister"
    create: true
    identifier_field: name
    slug: "{{fileNumber}}-{{slug}}" # the default for the slug is the identifier_field
    sortable_fields: ['fileNumber', 'name', 'course']  # use dot notation for nested fields
    summary: "{{fileNumber}} - {{name}} - {{instruments}} - {{course}}"
    fields:
      - {label: "NumeroFicheiro", name: "fileNumber", widget: "number"}
      - {label: "Nome" , name: "name", widget: "string"}
      - {label: "NomeCompleto" , name: "nameFull", widget: "string"}
      - {label: "NomeCivil", name: "nameC", widget: "string"}
      - {label: "Curso", name: "course", widget: "string"}
      - {label: "Madrinha", name: "godmother", widget: "string"}
      - {label: "Instrumentos", name: "instruments", widget: "list", hint: "Lista exemplo: Magister, Bandolim, Contrabaixo"}
      - {label: "Foto", name: "picture", widget: "string"}
  - label: "Atuais Mestre-Tunas"
    name: "atuais-mestre-tunas"
    folder: "_content/sobre-nos/membros/atualmente/mestre-tunas"
    create: true
    identifier_field: name
    slug: "{{fileNumber}}-{{slug}}"
    sortable_fields: ['fileNumber', 'name', 'course']  # use dot notation for nested fields
    summary: "{{fileNumber}} - {{name}} - {{instruments}} - {{course}}"
    fields:
      - {label: "NumeroFicheiro", name: "fileNumber", widget: "number"}
      - {label: "Nome" , name: "name", widget: "string"}
      - {label: "NomeCompleto" , name: "nameFull", widget: "string"}
      - {label: "NomeCivil", name: "nameC", widget: "string"}
      - {label: "Curso", name: "course", widget: "string"}
      - {label: "Madrinha", name: "godmother", widget: "string"}
      - {label: "Instrumentos", name: "instruments", widget: "list", hint: "Lista exemplo: Magister, Bandolim, Contrabaixo"}
      - {label: "Foto", name: "picture", widget: "string"}
  - label: "Atuais Tunas"
    name: "atuais-tunas"
    folder: "_content/sobre-nos/membros/atualmente/tunas"
    create: true
    identifier_field: name
    slug: "{{fileNumber}}-{{slug}}"
    sortable_fields: ['fileNumber', 'name', 'course']  # use dot notation for nested fields
    summary: "{{fileNumber}} - {{name}} - {{instruments}} - {{course}}"
    fields:
      - {label: "NumeroFicheiro", name: "fileNumber", widget: "number"}
      - {label: "Nome" , name: "name", widget: "string"}
      - {label: "NomeCompleto" , name: "nameFull", widget: "string"}
      - {label: "NomeCivil", name: "nameC", widget: "string"}
      - {label: "Curso", name: "course", widget: "string"}
      - {label: "Madrinha", name: "godmother", widget: "string"}
      - {label: "Instrumentos", name: "instruments", widget: "list", hint: "Lista exemplo: Magister, Bandolim, Contrabaixo"}
      - {label: "Foto", name: "picture", widget: "string"}
  - label: "Atuais Caloiras"
    name: "atuais-caloiras"
    folder: "_content/sobre-nos/membros/atualmente/caloiras"
    create: true
    identifier_field: name
    slug: "{{fileNumber}}-{{slug}}"
    sortable_fields: ['fileNumber', 'name', 'course']  # use dot notation for nested fields
    summary: "{{fileNumber}} - {{name}} - {{instruments}} - {{course}}"
    fields:
      - {label: "NumeroFicheiro", name: "fileNumber", widget: "number"}
      - {label: "Nome" , name: "name", widget: "string"}
      - {label: "NomeCompleto" , name: "nameFull", widget: "string"}
      - {label: "NomeCivil", name: "nameC", widget: "string"}
      - {label: "Curso", name: "course", widget: "string"}
      - {label: "Madrinha", name: "godmother", widget: "string"}
      - {label: "Instrumentos", name: "instruments", widget: "list", hint: "Lista exemplo: Magister, Bandolim, Contrabaixo"}
      - {label: "Foto", name: "picture", widget: "string"}
  - label: "Antigas Mestre-Tunas"
    name: "antigas-mestre-tunas"
    folder: "_content/sobre-nos/membros/sempre-tunafas/mestre-tunas"
    create: true
    identifier_field: name
    slug: "{{fileNumber}}-{{slug}}"
    sortable_fields: ['fileNumber', 'name', 'course']  # use dot notation for nested fields
    summary: "{{fileNumber}} - {{name}} - {{instruments}} - {{course}}"
    fields:
      - {label: "NumeroFicheiro", name: "fileNumber", widget: "number"}
      - {label: "Nome" , name: "name", widget: "string"}
      - {label: "NomeCompleto" , name: "nameFull", widget: "string"}
      - {label: "NomeCivil", name: "nameC", widget: "string"}
      - {label: "Curso", name: "course", widget: "string"}
      - {label: "Madrinha", name: "godmother", widget: "string"}
      - {label: "Instrumentos", name: "instruments", widget: "list", hint: "Lista exemplo: Magister, Bandolim, Contrabaixo"}
      - {label: "Foto", name: "picture", widget: "string"}
  - label: "Antigas Tunas"
    name: "antigas-tunas"
    folder: "_content/sobre-nos/membros/sempre-tunafas/tunas"
    create: true
    identifier_field: name
    slug: "{{fileNumber}}-{{slug}}"
    sortable_fields: ['fileNumber', 'name', 'course']  # use dot notation for nested fields
    summary: "{{fileNumber}} - {{name}} - {{instruments}} - {{course}}"
    fields:
      - {label: "NumeroFicheiro", name: "fileNumber", widget: "number"}
      - {label: "Nome" , name: "name", widget: "string"}
      - {label: "NomeCompleto" , name: "nameFull", widget: "string"}
      - {label: "NomeCivil", name: "nameC", widget: "string"}
      - {label: "Curso", name: "course", widget: "string"}
      - {label: "Madrinha", name: "godmother", widget: "string"}
      - {label: "Instrumentos", name: "instruments", widget: "list", hint: "Lista exemplo: Magister, Bandolim, Contrabaixo"}
      - {label: "Foto", name: "picture", widget: "string"}
  - label: "Antigas Caloiras"
    name: "antigas-caloiras"
    folder: "_content/sobre-nos/membros/sempre-tunafas/caloiras"
    create: true
    identifier_field: name
    slug: "{{fileNumber}}-{{slug}}"
    sortable_fields: ['fileNumber', 'name', 'course']  # use dot notation for nested fields
    summary: "{{fileNumber}} - {{name}} - {{instruments}} - {{course}}"
    fields:
      - {label: "NumeroFicheiro", name: "fileNumber", widget: "number"}
      - {label: "Nome" , name: "name", widget: "string"}
      - {label: "NomeCompleto" , name: "nameFull", widget: "string"}
      - {label: "NomeCivil", name: "nameC", widget: "string"}
      - {label: "Curso", name: "course", widget: "string"}
      - {label: "Madrinha", name: "godmother", widget: "string"}
      - {label: "Instrumentos", name: "instruments", widget: "list", hint: "Lista exemplo: Magister, Bandolim, Contrabaixo"}
      - {label: "Foto", name: "picture", widget: "string"}
  # homepage
  - label: "Contactos"
    name: "contactos"
    folder: "_content/homepage/contactos"
    create: true
    identifier_field: fileName
    slug: "{{fileName}}"
    fields:
      - {label: "Titulo do Ficheiro", name: "fileName", widget: "string"}
      - {label: "Nome RP" , name: "nameRP", widget: "string"}
      - {label: "Contacto RP" , name: "mobileRP", widget: "string"}
      - {label: "Nome Magister", name: "nameMagister", widget: "string"}
      - {label: "Contacto Magister", name: "mobileMagister", widget: "string"}
      - {label: "Email TUNAFE", name: "email", widget: "string"}
      - {label: "Morada TUNAFE", name: "address", widget: "string"}
  - label: "Ensaios"
    name: "ensaios"
    folder: "_content/homepage/ensaios"
    create: true
    identifier_field: fileName
    slug: "{{fileName}}"
    fields:
      - {label: "Titulo do Ficheiro", name: "fileName", widget: "string"}
      - {label: "Dias da semana" , name: "weekDays", widget: "string"}
      - {label: "Sala de ensaio" , name: "rehearsalRoom", widget: "string"}
      - {label: "Sala da Tuna", name: "tunaRoom", widget: "string"}
      - {label: "Hora inicio ensaio", name: "startTime", widget: "string"}
      - {label: "Hora fim ensaio", name: "finishTime", widget: "string"}
